editor-bootstrap/vim-bootstrap

README.md
This way the instructions is more clearly and in a one copy and paste i install all pre-requisites.
=> Installation instructions more clearly

vim_template/vimrc
I remove the alias of *<leader>s* to remove whitespaces because this is not in README.md but if you want create at just put <leader>s to :FixWhitespace.
Sorry for the english but google translate help me in this adventure hehe
=> Fix #85 Add trailing whitespace as plugin.

vim_template/vimrc
=> Fix airline tabline icons and undefined or ugly symbols

vim_template/vimrc
=> create new let check finsh install neobundle

vim_template/vimrc
=> Fixed #112

vim_template/vimrc
Set compatibility for power line fonts in airline.
=> Fix airline compatility #104

README.md, vim_template/langs/ruby/ruby.vim
Use spec maps to run spec tests
=> Use spec maps

vim_template/vimrc
=> Add ctrlp-py-matcher for CtrlP improves

vim_template/vimrc
Using J and K for move up and down.
Tip:
http://vimrcfu.com/snippet/77
=> Move visual block up or down easily

vim_template/vimrc
Add a plugin that auto-close brackets, quotes, parens and gives a way to easily insert or delete them.
=> Add plugin auto-pairs to insert or delete brackets, quotes, parens in pairs

vim_template/vimrc
Sorry, my bad! Somehow I screwed up the Powerline symbols in my previous commit. This will fix them.
=> Fix up Powerline symbols

vim_template/vimrc
=> Improve NERDTree usability

vim_template/vimrc
Using ag to improve ctrlp, let use --ignore regex.
=> ctrlp ag use same regex, session <Space> on open and save

README.md
=> Update README with curl example

vim_template/vimrc
=> remove option term on neovim config

vim_template/langs/python/python.vim
for more informations check:
https://github.com/Yggdroot/indentLine/issues/125
https://github.com/Yggdroot/indentLine/issues/58
=> add some configs (and improves) for IndentLine plugin

vim_template/vimrc
Don't merge yet. We need a aditional config that i don't know how to do it. See: #170 and [this](http://felixge.de/2013/08/08/vim-trick-open-current-line-on-github.html)
=> Support "open file in github" in linux

vim_template/vimrc
I order to avoid external configuration to work, i found this solution using vim-fugitive.
=> Using vim-fugitive to open current line on github

README.md
I tested here and the packages names are the same.
=> Check package name on Debian Fix #131

vim_template/vimrc
=> Fix visualbell

README.md
=> Add pre-requisites on fedora

README.md
Add python-jinja to fedora requirements
=> Add python-jinja to fedora requirements

README.md
Improve README hotkey table titles to emphasis click action.
=> Improve README design

vim_template/langs/go/go.vim
- new shortcuts
- better syntax highlight
- fix some behaviour(like preview)
=> Better vim-go shortcuts

vim_template/vimrc
See http://vim.wikia.com/wiki/Speed_up_Syntax_Highlighting
=> Speed up syntax highlighting

vim_template/vimrc
=> Center screen when finding with "n/N".

web/web.go
update submodules to lastest commit on hook
=> update submodules on hook

vim_template/vimrc
=> checker exist curl

README.md, vim_template/langs/elm/elm.bundle, vim_template/langs/elm/elm.vim
This PR intends to add support for [Elm](http://elm-lang.org) in vim-bootstrap. I'm pretty new to vim-bootstrap source and to Go so I might have forgotten some stuff. Drop a line and I'll do by best to cover whatever was left behind ; )
=> Add tempate for Elm

vim_template/langs/go/go.vim
code already present in https://github.com/fatih/vim-go/blob/master/ftplugin/go/tagbar.vim
=> remove duplicated code

vim_template/langs/go/go.vim
- remove go_auto_type_info due to performance issues, use \<leader\>i instead.
- reduce also the linter list  due to performance issues
=> bugfix: performance issues

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md
=> Minor wording fix

README.md
Resolves #273.
I missed information, or at least more information, regarding customization. By navigating inside the generated file, I realized which are the recommended entries. Now, they have their own README section, pointing the path and respective content.
=> Add customization section

vim_template/vimrc
Avoid <F3> shortcut prints nerdtree command every time
=> Silence NERDTreeToggle command

vendor/github.com/gorilla/mux/README.md, vendor/github.com/gorilla/mux/doc.go, vendor/github.com/gorilla/mux/mux.go, vendor/github.com/gorilla/mux/regexp.go, vendor/github.com/gorilla/mux/route.go, vendor/github.com/urfave/negroni/README.md, vendor/github.com/urfave/negroni/logger.go, vendor/github.com/urfave/negroni/negroni.go, vendor/github.com/urfave/negroni/recovery.go, vendor/github.com/urfave/negroni/response_writer.go, vendor/github.com/urfave/negroni/response_writer_pusher.go, vendor/vendor.json
Third party packages are never updated.
=> Updated third party packages

README.md
Resolves #275 for good with install instructions being added to README.
=> Update README with openSUSE install instructions

vim_template/langs/javascript/javascript.vim
The autocmd should only change the configuration of the current file
=> javascript: autocmd should use setlocal command

README.md, vim_template/vimrc
Shortcut for recovery commands from history through FZF.
=> quickly history commands from FZF

vim_template/vimrc
Explanation about this [PR](#306).
=> Fix #306: remove 'wrong' configs

README.md
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
=> The project's website doesn't work with 'www' prefix

README.md
Just a small correction to the opening sentence.
=> Corrected grammar in README.md

vim_template/vimrc
https://github.com/avelino/vim-bootstrap/issues/320
=> improve windows automatical

generate/generate.go
=> neovim generate, check 2 condition name

README.md, vim_template/langs/php/php.bundle, vim_template/langs/php/php.vim
1. Added Phpactor is a better tool implementation php for vim
2. Added php-cs-fixer a tool to automatically fix PHP Coding Standards
=> Add some plugins for support php

template/assets/css/style.css
Fix the Carbon Ads style on the homepage with better readibility. See the expected result:
=> Update carbon styles

README.md, template/index.html
In proposing this because the link changed and my access was blocked by the company antivirus because of the xxx domain.
=> Change vim church link

Dockerfile
This bug was introduced by #339 and reported in #341 . These changes will fix the container. Thanks @avelino to report!
=> Fix dockerfile bug introduced by binary split

generate/bindata.go, template/index.html
close #346 
Add icon "Fork me on Github"
=> Add "Fork me on Github" icon

cmd/vim-bootstrap-server/vim-bootstrap-server.go, web/web.go
This PR solves the #351 issue. I added function and route for serve favicon.
=> Add function for serve favicon

generate/bindata.go, vim_template/themes/vadelma/vadelma.bundle, vim_template/themes/vadelma/vadelma.vim
=> Add new theme vadelma

generate/bindata.go, vim_template/themes/wombat/wombat.bundle, vim_template/themes/wombat/wombat.vim
=> Add theme wombat

README.md
Add command to install the FreeBSD dependencies via packages collection
=> Add FreeBSD dependencies

generate/generate.go
=> fix: data race in VimBuffer

generate/vim_template/vimrc
Update git commands to stop show warnings and deprecated commands
=> Update Git commands

generate/vim_template/vimrc
I added some vimrc settings that are considered essential settings, I added mouse support(like clickable tabs and moving cursor with mouse), wildmenu support, and also ignored node_modules in nerdtree.
=> Added some vimrc essential settings

.github/PULL_REQUEST_TEMPLATE.md
Change master branch references with main.
=> Change master references with main

template/index.html
Including title images for show text on mouse hover.
Change alt value.
=> fix: Adding title image

generate/vim_template/themes/sonokai/sonokai.bundle, generate/vim_template/themes/sonokai/sonokai.vim
=> Add new theme sonokai

generate/vim_template/themes/badwolf/badwolf.bundle, generate/vim_template/themes/badwolf/badwolf.vim
Add new theme badwolf.
Fix #415
=> Add new theme badwolf

generate/vim_template/themes/catppuccin/catppuccin.bundle, generate/vim_template/themes/catppuccin/catppuccin.vim
=> Add theme catppuccin
