vim_template/langs/python/python.vim, vim_template/vimrc
Remove duplicate entries of ``set backspace`` and ignore **W391** on flake8 check, because this PEP8 has conflict with **W292** on VIM.
=> Remove duplicate and ignore W391 (PEP8)

vim_template/vimrc
Set a `vim_bootstrap_editor` variable for get the actual editor (vim or nvim). 
It's very important for `:VimBootstrapUpdate` command uses.
=> Create vim_bootstrap_editor variable on vimrc template

vim_template/vimrc
When I was starting vim, I was getting this warning:
The variable g:airline_enable_syntastic is deprecated and may not work in the future. It has been replaced with g:airline#extensions#syntastic#enabled....
=> Update airline deprecated syntax

README.md, vim_template/vimrc
Small change to functionalities:
- **git add**: now adds only *current* file.
Old command added every file in the path which wasn't on the gitignore file, this is troublesome, specially for beginners
- **git commit**: splits window for commit message.
Old command could try to create a commit with empty message, if user was careless.
=> Change git commands to fugitive commands

vim_template/vimrc
Neovim removed the ttyfast option so remove it from the generated
template.  See neovim change:
https://github.com/neovim/neovim/commit/10b2a0e52980aba2d1efc072368fcaf1f33e7512
=> Remove ttyfast option from neovim

README.md, vim_template/vimrc
WOW! NeoVim has now a built-in terminal! :beer: 
http://neovim.org/doc/user/nvim_terminal_emulator.html#nvim-terminal-emulator
I guess vim-users can still use vim.shell plugin and neovim-users can use this new feature with `,sh` command instead of vim.shell.
=> Add support for NeoVim terminal emulation

vim_template/vimrc
This fix a warning when vim starts because of some deprecated variables
"The variable g:airline_branch_prefix is deprecated and my not work in
the future..."
=> Fix deprecated airline config name

vim_template/vimrc
Fixes the following error:
```
UltiSnips requires Vim >= 7.4
Press ENTER or type command to continue
```
=> Fix UltiSnips error when using vim 7.3

generate.py
Hey,
Vim-Bootstrap generation was giving 500 internal server error so i thought i would use the same code in the web request handler for generation inside a CLI script. This could be handy to people who want to take the code offline and generate vimrc's.
Added a generate script that takes a list of languages and generates then spits out the vimrc file content. This could be improved by using a CLI library to have options for output files, languages .. etc
=> Generate vim-bootstrap CLI

vim_template/vimrc
Actions on conveniece variables need to happen after .vimrc.local has
been sourced, otherwise the user has no chance to set convenience
variables in time.
This fixes https://github.com/avelino/vim-bootstrap/issues/158
=> Fix conveniece variables

editors.py, generate.py, main.py, vim_template/vimrc
Neovim has moved to using XDG Base directories which means the base directory
moved to ~/.config/nvim.
This moves all ~/.nvimXX to newer versions in ~/.config/nvim.
=> Support nvim's new XDG ./config dirs

vim_template/vimrc
With cache CtrlP works really fine in big projects. If you want refresh the cache just press F5 with CtrlP opened.
CtrP use vim native globpath() for search files. If you have Ag installed in your machine, search files will be more fast. See the explanation: http://stackoverflow.com/a/22784889
=> Improve CtrlP speed with cache and Ag

vim_template/langs/python/python.vim
New version of jedi plugin, causes a duplicated import when you copy and paste code to vim, Example:
`from math import import sin`
Avoid this with new config:
`let g:jedi#smart_auto_mappings = 0`
Thank you @gtsalles for the tip.
=> Avoid duplicated imports in python file

vim_template/vimrc
more than 1 year was opened a PR and we had no return of the @sherzberg
so I decided to keep a fork of official (thus keeping the credit of creator)
PR: https://github.com/sherzberg/vim-bootstrap-updater/pull/4 by @nemith
Accept PR in: https://github.com/avelino/vim-bootstrap-updater/commits/master
=> set avelino fork repo official vim-bootstrap-updater package

vim_template/langs/python/python.vim
After many test I come to the conclusion that it's not a a bug or an inconsistency in flake8, sorry for my old PR ( #87 )
=> remove "ignore=W391" in syntastic plugin config

vim_template/vimrc
When using double quotes when it tried to source the file we get an error.
=> Fix load of local vimrc and local vim bundle

generate/generate.go, glide.yaml, vim-bootstrap.go
Neovim follows xdg style directories which means that all files
live under ~/.config/nvim.  When the generator was switches to go
the assumptions was that the config files were named the same as
vim but just under .config.  This assumption is incorrect.
This restores the same functionality and names as the previous
python generator.
Basedir      : ~/.config/nvim
Main rc file : ~/.config/nvim/init.vim
Local rc file: ~/.config/nvim/local_init.vim
Local bundle : ~/.config/nvim/local_bundles.vim
=> Update config files paths for neovim

vim_template/langs/go/go.vim
Older versions of vim do not have CompleteDone. Test vim version before attempting to use CompleteDone.
=> Prevent E216 error on older versions of vim

vim_template/vimrc
many people like to use others shell emulators like oh my zsh, I changed the vimrc to use the global variable $SHELL for use my own shell emulator.
=> changing the vimrc to accept my own shell emulator

vim_template/vimrc
Use fzf instead of ctrlp plugin. fzf is faster and has more resources. 
I choose --bin option to avoid system replaces(like ctrl+r).
Another decision is to not replace grep.vim as proposed in #244 because it only works if silver_archer is installed. If we found a solution for that, we can do the replacement.
=> Replace ctrlp with fzf

vim_template/langs/python/python.bundle
I added 'requirements.txt.vim' to Python's vim_template. 
Users can edit 'requirements.txt.vim' like this:
I am the author of that plugin and I am sympathizing with the Vim Bootstrap project.
=> Add 'requirements.txt.vim' in Python's vim-template

vim_template/langs/ruby/ruby.vim
Check if running on neovim or vim, and correctly loads matchit package.
=> Bugfix: matchit not found in neovim. Fix #257

vim_template/langs/go/go.vim
Improvements in go based on [this](https://medium.com/@sebdah/my-neovim-setup-for-go-7f7b6e805876) post.
Add softtabstop, because if softtabstop equals tabstop and expandtab is not set, vim will always use tabs.
Add more linters on gometalinter.
Auto type info to move the cursor over a variable or such to see what type it is. Or move it to a function call and see it’s input parameters and return values.
More highlights, If it affects performance, we can rethink this.
=> Go improvements based on a post

vim_template/langs/go/go.vim
Removing setting that is standard now. Looks: https://github.com/fatih/vim-go/pull/1365
=> Quicklist is now default

vim_template/langs/scala/scala.bundle
If your vim is not compiled with python2 support an error is handled with  this plugin.
=> [scala] sbt.vim is not working with python 3

vim_template/langs/go/go.vim
Add shortcuts for goDeclsDir, now it works in vim-bootstrap https://github.com/fatih/vim-go/pull/1437
=> Add shortcuts for goDeclsDir

vim_template/langs/go/go.vim
As `<C-f>` is an useful navigation shortcut, i propose to change GoDeclsDir shortcut to `<leader>dr` .
=> Change shortcut for GoDeclsDir

vim_template/vimrc
For neovim, we must store plug.vim under ~/.config/nvim/autoload
=> Use Config.BaseDir for autoload plug script

vim_template/langs/html/html.bundle
The Github user name for the author of vim-coloresque has changed. This causes issues when trying to run `PlugInstall`, giving the following error:
```x vim-coloresque:
Invalid URI: https://github.com/gko/vim-coloresque.git
Expected:    https://github.com/gorodinskiy/vim-coloresque.git
PlugClean required.
```
This PR fix that by changing the user name from `gorodinskiy` to `gko`.
=> UPDATE vim-coloresque AUTHOR USER NAME

vim_template/vimrc
`scrolloff` causes unexpected scrolling behaviour in terminal mode.
`scrolloff=3` can be kept on for everything else.
See https://github.com/neovim/neovim/issues/11072
Vim8 doesn't have this behaviour so only needs to be set for nvim.
=> Disable scrolloff for Neovim Terminal mode

vim_template/langs/ruby/ruby.bundle
Problem: failure to pull plugin `vim-ruby-refactoring` when execute PlugInstall for generated vimrc to use with ruby language.
The Github repository of `ecomba/vim-ruby-refactoring` has changed its default branch from `master` to `main`. This change add tag to the plugin so it will pull the `main` branch instead of the default `master`.
=> Add tag to vim-ruby-refactoring in ruby.bundle template

web/web.go
=> Use timestamp instead of commit hash in version

cmd/vim-bootstrap-server/vim-bootstrap-server.go, web/web.go
Function web.HandleHook is not used anymore.
=> Remove function HandleHook and references because is deprecated.

README.md
Just noticed a little typo on line 177: "clone file" instead of "close file".
=> fix typo on line 177

generate/vim_template/vimrc
Gcommit is deprecated in favor of Git commit
At least, this is the message that appears when I type <Leader>gc in NeoVim. Using **:Git commit** directly seems to work without any issues and the **--verbose** flag makes the commit easier to write because it shows the difference on the bottom of the message, however this flag is totally optional.
=> Update deprecated command

generate/vim_template/langs/php/php.vim
Update some deprecated commands from phpactor which are not working anymore, from what I can see the other commands seem to be working.
I searched the documentation to see the alternatives and it seems that these ones do the job appropriately.
`:help phpactor`
_phpactor-commands_ section
=> Update deprecated commands

README.md
Since Fedora 35 `ctags-etags` package has been replaced by `ctags`, see:
https://fedora.pkgs.org/35/fedora-x86_64/ctags-5.9-1.20210725.0.fc35.x86_64.rpm.html
=> Fix wrong ctags package name for Fedora

template/index.html
- download a `generate.vim` from https://vim-bootstrap.com/ after choosing "neovim" and "go"
- open vim
[Google results](https://github.com/editor-bootstrap/vim-bootstrap/issues/178): 
At this point I'm thinking "Ooookaaay, so why am I still getting vim settings even though I chose neovim"
Reason: The vimrc template [checks for `nvim`](https://github.com/editor-bootstrap/vim-bootstrap/blob/main/generate/vim_template/vimrc#L174):
...but `index.html`s `value` for editor [is `neovim`](https://github.com/editor-bootstrap/vim-bootstrap/blob/main/template/index.html#L186)
- use `nvim` in the html template, not `neovim`. This is what the value was before https://github.com/editor-bootstrap/vim-bootstrap/pull/381
=> fix: use value of `nvim` instead of `neovim`

generate/vim_template/vimrc
The value type for `g:indentLine_concealcursor` is currently wrong (it should be a `string`, not a `number`), causing the `indentLine` plugin to throw an error starting with VIM 8.2, possibly because type checking became stricter in that version of VIM?
This fixes it by changing the value from `0` to `''`.
=> Fix invalid indentLine_concealcursor value type breaking VIM 8.2 (#406)

template/assets/css/style.css, template/index.html
Hey, while browsing https://vim-bootstrap.com/, I was struggling mentally to match the languages/frameworks icons with their name. I thought it would be nice to add them, as it's done for the themes below.
Here's are my changes:
- Add labels to langs & frameworks
- Align center themes labels
Let me know if I can do something else :)
---
**Before**
**After**
**Before**
**After**
**Before**
**After**
<details>
<summary><b>Before</b> (open ⤵️)</summary>
</details>
<details>
<summary><b>After</b> (open ⤵️)</summary>
</details>
=> Add labels to languages and frameworks

template/assets/css/style.css, template/index.html
- Fixed the issue on the landing page, where the `Product hunt` button is not aligned. Refer to the image below
- Improved it to 
It's a minor change but you don't want your home page to look unaligned and unlooked for ;).
=> fixed product hunt button alignment issue

template/assets/css/style.css
This PR fixes the overflow caused by theme selector, as mentioned in the issue #418 
Introduced a scroll bar to overcome the overflow.
**Screenshot**
=> fix: horizontal overflow

template/index.html
Resolved some of the HTML markup issues highlighted by w3 validator
=> Fixed HTML markup issues in index.html

generate/vim_template/themes/onedark/onedark.bundle, generate/vim_template/themes/onedark/onedark.vim
One Dark theme originated from the Atom text editor. This uses [onedark.vim](https://github.com/joshdick/onedark.vim) for the theme.
=> Add new theme onedark

generate/vim_template/themes/material/material.bundle, generate/vim_template/themes/material/material.vim
Add the [material theme](https://github.com/kaicataldo/material.vim) to vim-bootstrap, following the [README guidelines for adding a new theme](https://github.com/editor-bootstrap/vim-bootstrap#adding-a-new-theme) and previous PRs like [this one](https://github.com/editor-bootstrap/vim-bootstrap/pull/425). Tested locally with `./vim-bootstrap -langs=go -editor=vim -theme=material > ~/.vimrc`
=> Add material theme

generate/vim_template/themes/solarized/solarized.bundle, generate/vim_template/themes/solarized/solarized.vim 
This PR adds the possibility to select the `solarized` theme when choosing the theme to install as part of the generated `.vimrc` file.
=> Add the option of choosing the solarized theme when selecting the theme

generate/vim_template/vimrc
This PR targets issue #431. 
The old command `:Gbrowse` is replaced by the new one `:GBrowse`
=> Fixes removed `:Gbrowse` command - Issue #431

template/assets/css/style.css
This PR fixes the height of the cards, as mentioned in the issue #417 
**Description**
Added CSS styling to card to fix the height of the cards
**Screenshot**
=> fix: fixing height of cards

cmd/vim-bootstrap-server/vim-bootstrap-server.go, cmd/vim-bootstrap/vim-bootstrap.go, generate/generate.go, generate/plugins.go, generate/plugins.json, generate/vim_template/vimrc, template/assets/css/style.css, template/assets/js/form.js, template/index.html, web/web.go
- Expose new HTTP endpoints in the server for:
- Listing all plugins (`/plugins`)
- Listing plugin categories (`/plugin-categories`)
- Validating plugin selections (`/validate-plugins`)
- Add `--additional-plugins` CLI flag to vim-bootstrap generator for specifying extra plugins
- Wire up backend logic to support plugin data and validation
fixed: #101
fixed: #100
fixed: #98
fixed: #96
fixed: #92
fixed: #80
Please check the following:
1. Make sure you are targeting the `main` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/editor-bootstrap/vim-bootstrap/blob/main/.github/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)
**You MUST delete the content above including …
=> Add plugin management API endpoints and CLI flag
